repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.36.0
  hooks:
    - name: check-jsonschema-events
      id: check-jsonschema
      files: ^_data/events.json$
      args: ["--base-uri", ".", "--schemafile", "_schemas/events.json"]
    - name: check-jsonschema-people
      id: check-jsonschema
      files: ^_data/people.json$
      args: ["--base-uri", ".", "--schemafile", "_schemas/people.json"]
    - name: check-jsonschema-publications
      id: check-jsonschema
      files: ^_data/publications.json$
      args: ["--base-uri", ".", "--schemafile", "_schemas/publications.json"]
- repo: local
  hooks:
    - name: check-keys
      id: check-keys
      language: python
      entry: python3 _schemas/check_keys.py
      files: ^_data/.*.json$


