url: "https://the-bda.team"

description: >-
  The BDA Team addresses challenges of modern society via basic research and infrastructure development.

exclude:
  - README.md
  - LICENSE
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - _schemas/

liquid:
  error_mode: strict

months:
  jan: January
  feb: February
  mar: March
  apr: April
  may: May
  jun: June
  jul: July
  aug: August
  sep: September
  oct: October
  nov: November
  dec: December

